# Generated by Django 5.1.5 on 2025-01-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABOUT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Job_Role', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
