# Generated by Django 5.1.5 on 2025-01-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmins', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABOUT_ME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desc', models.CharField(max_length=100)),
            ],
        ),
    ]
