# Generated by Django 5.1.5 on 2025-01-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmins', '0004_about_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='RESUME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resume_desc', models.CharField(max_length=100)),
                ('Resume_link', models.CharField(max_length=100)),
            ],
        ),
    ]
