# Generated by Django 5.1.5 on 2025-01-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmins', '0005_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='EXPERENCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Years', models.CharField(max_length=100)),
                ('Skill', models.CharField(max_length=100)),
                ('Devlopment', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=100)),
                ('heading_info1', models.CharField(max_length=100)),
                ('heading_info2', models.CharField(max_length=100)),
                ('heading_info3', models.CharField(max_length=100)),
            ],
        ),
    ]
