# Generated by Django 5.1.5 on 2025-01-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmins', '0006_experence'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDUCATIONS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_year', models.CharField(max_length=100)),
                ('Degree', models.CharField(max_length=100)),
                ('University', models.CharField(max_length=100)),
                ('Grade', models.CharField(max_length=100)),
            ],
        ),
    ]
