# Generated by Django 5.1.5 on 2025-01-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmins', '0007_educations'),
    ]

    operations = [
        migrations.CreateModel(
            name='PROJECT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_Projects', models.ImageField(upload_to='static/admin/img')),
                ('Projects_Name', models.CharField(max_length=100)),
                ('Projects_Info', models.CharField(max_length=100)),
                ('Projects_Link', models.CharField(max_length=100)),
            ],
        ),
    ]
